In [66]:
import numpy as np

In [67]:
X = np.ones((3,20))

In [68]:
X.shape

(3, 20)

In [69]:
X

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [70]:
X[0][0] = 2

In [71]:
X

array([[ 2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [72]:
X[0][0] = 1.0

In [73]:
X

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [74]:
X[0,0] = 2

In [75]:
X

array([[ 2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [76]:
W1= np.array([1,2,3])

In [77]:
W1

array([1, 2, 3])

In [78]:
W1.shape

(3,)

In [79]:
X.shape

(3, 20)

In [84]:
b1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [85]:
b1.shape

(20,)

In [86]:
H1 = np.maximum(0, np.dot(W1,X) + b1)

In [87]:
H1

array([  8.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,
        18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.])

In [88]:
p = 0.5

In [94]:
H1.shape

(20,)

In [103]:
U1 = np.random.rand(*H1.shape) < p

In [104]:
U1

array([ True, False,  True,  True, False, False, False,  True,  True,
       False,  True, False, False, False, False,  True, False,  True,
       False, False], dtype=bool)

In [105]:
U1

array([ True, False,  True,  True, False, False, False,  True,  True,
       False,  True, False, False, False, False,  True, False,  True,
       False, False], dtype=bool)

In [106]:
H1

array([  8.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,
        18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.])

In [107]:
H1 *= U1

In [108]:
H1

array([  8.,   0.,   9.,  10.,   0.,   0.,   0.,  14.,  15.,   0.,  17.,
         0.,   0.,   0.,   0.,  22.,   0.,  24.,   0.,   0.])

In [2]:
import numpy as np
a = np.ones((3,5,5))

In [3]:
a.shape

(3, 5, 5)

In [4]:
b = np.ones((5,5,3))

In [5]:
b.shape

(5, 5, 3)

In [6]:
c = np.dot(a,b)

In [16]:
c.shape

(3, 5, 5, 3)

In [17]:
c.ndim

4

In [8]:
b.T.shape

(3, 5, 5)

In [9]:
a = np.ones((2,3,4))

In [10]:
a.shape

(2, 3, 4)

In [11]:
a.T.shape

(4, 3, 2)

In [12]:
b = np.ones((3,4,5))

In [13]:
b.shape

(3, 4, 5)

In [15]:
np.dot(a,b).shape

(2, 3, 3, 5)