In [2]:
import numpy as np
a = np.ones((2,5))

In [3]:
a.shape

(2, 5)

In [4]:
b = np.ones(5)

In [5]:
b.shape

(5,)

In [6]:
c = a + b

In [7]:
c.shape

(2, 5)

In [8]:
c

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [9]:
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [10]:
b

array([ 1.,  1.,  1.,  1.,  1.])