In [1]:
import numpy as np

In [2]:
a = np.arange(5)

In [7]:
a

array([0, 1, 2, 3, 4])

In [3]:
hist, bin_edges = np.histogram(a, density=True)

In [4]:
hist

array([ 0.5,  0. ,  0.5,  0. ,  0. ,  0.5,  0. ,  0.5,  0. ,  0.5])

In [8]:
bin_edges

array([ 0. ,  0.4,  0.8,  1.2,  1.6,  2. ,  2.4,  2.8,  3.2,  3.6,  4. ])

In [5]:
hist.sum()

2.4999999999999996

In [6]:
np.sum(hist*np.diff(bin_edges))

1.0